#!/usr/bin/env fish

# Set DOTFILES to the absolute path of this script
set DOTFILES (cd (dirname (status --current-filename)) && pwd)

# ==================================================
# Update this with all programs
# ==================================================
set programs fish ghostty

# Function to link the directory from dotfiles to into a subdirectory in .config
function linkConfig
    if test -d "$HOME/.config/$argv"
        mv "$HOME/.config/$argv" "$HOME/.config/$argv-backup"
    end
    ln -s "$DOTFILES/$argv" "$HOME/.config/$argv"
end

# Run linkConfig for all programs
for x in $programs
    linkConfig $x
end

# ==================================================
# Setup Terminal with Fish
# ==================================================

# Install Fisher package manager for fish
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

# Install and configure Tide prompt for fish
fisher install IlanCosman/tide@v6
tide configure --auto --style=Lean --prompt_colors='True color' --show_time='12-hour format' --lean_prompt_height='Two lines' --prompt_connection=Dotted --prompt_connection_andor_frame_color=Light --prompt_spacing=Sparse --icons='Few icons' --transient=No
