#!/usr/bin/env fish

# Set DOTFILES to the absolute path of this script
set DOTFILES (cd (dirname (status --current-filename)) && pwd)

# ==================================================
# Install programs
# ==================================================

# ==========
# Terminal
# ==========
brew install neovim
brew install lazygit

# Mac App Store Automation
brew install mas

# Github cli
brew install gh

# Yazi
brew install yazi ffmpeg sevenzip jq poppler fd ripgrep fzf zoxide resvg imagemagick font-symbols-only-nerd-font

# ==========
# GUI
# ==========
brew install --cask adguard
brew install --cask alt-tab
brew install --cask arc
brew install --cask dbngin
brew install --cask docker-desktop
brew install --cask ghostty
brew install --cask herd
brew install --cask mac-mouse-fix
brew install --cask monitorcontrol
brew install --cask phpstorm
brew install --cask shottr
brew install --cask raycast
brew install --cask rectangle
brew install --cask tableplus
brew install --cask transmit
brew install --cask zed
brew install --cask zoom

# Amphetamine
mas install 937984704

# Bitwarden
mas install 1352778147

# Craft
mas install 1487937127

# Dropover
mas install 1355679052

# Slack
mas install 803453959

# ==================================================
# Setup Terminal with Fish
# ==================================================

# Fisher package manager for fish
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

# Tide prompt for fish
fisher install IlanCosman/tide@v6

# Install Sponge (remove typos from command history)
fisher install meaningful-ooo/sponge

# ==================================================
# Copy configs for programs
# ==================================================

# update this with all programs that have configs to copy
set programs fish ghostty nvim

# Function to link the directory from dotfiles to into a subdirectory in .config
function linkConfig
    if test -d "$HOME/.config/$argv"
        mv "$HOME/.config/$argv" "$HOME/.config/$argv-backup"
    end
    ln -s "$DOTFILES/$argv" "$HOME/.config/$argv"
end

# Run linkConfig for all programs
for x in $programs
    linkConfig $x
end

# Configure terminal prompt
tide configure --auto --style=Lean --prompt_colors='True color' --show_time='12-hour format' --lean_prompt_height='Two lines' --prompt_connection=Dotted --prompt_connection_andor_frame_color=Light --prompt_spacing=Sparse --icons='Few icons' --transient=No
