#!/usr/bin/env zsh

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty
echo "Added Kitty"

rm -rf $HOME/.wezterm.lua
ln -s $DOTFILES/wezterm/.wezterm.lua $HOME/.wezterm.lua
echo "Added WezTerm"
